from enum import Enum

class SensorTypes(str, Enum):
    Temperature = "Temperature"
    Humidity = "Humidity"
    Pressure = "Pressure"
    Flow = "Flow"
    Volume = "Volume"
    GasComposition = "GasComposition"
    LiquidComposition = "LiquidComposition"
    Vibration = "Vibration"
    Noise = "Noise"
    Corrosion = "Corrosion"
    GasDetection = "GasDetection"
    FlameDetection = "FlameDetection"
    LevelIndicator = "LevelIndicator"
    ValveStatus = "ValveStatus"
    PumpStatus = "PumpStatus"
    CompressorStatus = "CompressorStatus"
    PowerConsumption = "PowerConsumption"
    WaterContent = "WaterContent"
    OxygenContent = "OxygenContent"
    HydrogenSulfideContent = "HydrogenSulfideContent"
    CarbonDioxideContent = "CarbonDioxideContent"
    ParticulateMatter = "ParticulateMatter"
    LeakDetection = "LeakDetection"
